name: My first Workflow

on: push 

jobs: 
    First-job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v7
          
        - name: welcome message
          run: echo "My first workflow"

        - name: list files
          run: ls

        - name: read file
          run: cat README.md